[platformio]
default_envs = pic12f683

[env:pic12f683]
platform = file://C:/Users/nano/Documents/platformio-microchip-xc8
board = pic12f683
framework = xc8
upload_protocol = pickit3

; XC8, DFP e IPECMD s\u00e3o detectados automaticamente no Windows.
; Use custom_xc8_path, custom_dfp_path e custom_ipecmd_path somente para sobrescrever.
