[platformio]
default_envs = pic12f675

[env:pic12f675]
platform = file:///Users/ijmeca/Documents/AI-PLATFORMIO/platform-microchip8
board = pic12f675
framework = xc8

custom_xc8_path = /Applications/microchip/xc8/v3.10
custom_dfp_path = /Applications/microchip/mplabx/v5.45/packs/Microchip/PIC10-12Fxxx_DFP/1.3.46/xc8
